name: Merge Request into dev or master
on:
  push:
    branches:
    - 'dev'
  pull_request:
    types: [opened, edited, reopened]
    branches:
    - ['dev', 'master']

jobs:
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build stage node application
      run: npm ci --omit=dev && npm run build && cp ~/actions-runner/.envstage ~/actions-runner/_work/daily-art-backend/daily-art-backend/.env

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_REGISTRY_SECRET }}

    - name: Build container image
      run: echo ${{ secrets.USER_PASSWORD }} | sudo -S docker build -t registry.digitalocean.com/dailyirasuto-backend-images/dailyart:production-update .

    - name: Run docker contianer
      run: . ./.github/workflows/runBlue.sh