name: Merge Request Master
on:
  push:
    branches:
    - 'dev'
  pull_request:
    types: [opened, edited, reopened]
    branches:
    - 'master'

jobs:
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:

    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Buil node application
      run: npm run build

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_REGISTRY_SECRET }}

    - name: Build container image
      run: docker build -t registry.digitalocean.com/dailyirasuto-backend-images/dailyart:staging .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/dailyirasuto-backend-images/dailyart:staging
