name: Run Jest Tests

on:
  push:
    branches:
    - '**'


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: npm ci && npm run test